plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.cstewart.android.trycamel'
    compileSdk 37

    defaultConfig {
        applicationId "com.cstewart.android.trycamel"
        minSdk 23
        targetSdk 36
        versionCode 14
        versionName "2.0.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.viewpager2

    testImplementation libs.junit
    testImplementation libs.robolectric
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
}
